### ISSUE TITLE
Incorrect entries in column for assays

### ISSUE THREAD

**Issue by hansenp** [monarch-initiative/SLDBGen#199]
In the generated table `SL_data.tsv` in the column `assay` there are 178 incorrect entries, with an additional `RCC4(Table-S5)` or `786-0(Table-S4)` appended to the name of the assay.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/10495485/146037617-cca97592-84ac-46d0-9d3e-0330353ccafc.png">

**Comment by pnrobinson** [comment]
fixed
